import type {
  ArticleCard,
  ProductCard,
  TrendingTopic,
} from "@/lib/content/types";

export const contentImages = {
  iphone:
    "https://images.unsplash.com/photo-1695048133142-1a20484d2569?auto=format&fit=crop&w=1600&q=80",
  iphoneAlt:
    "https://images.unsplash.com/photo-1510557880182-3d4d3cba35a5?auto=format&fit=crop&w=1600&q=80",
  galaxy:
    "https://images.unsplash.com/photo-1610945415295-d9bbf067e59c?auto=format&fit=crop&w=1600&q=80",
  pixel:
    "https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?auto=format&fit=crop&w=1600&q=80",
  macbook:
    "https://images.unsplash.com/photo-1517336714731-489689fd1ca8?auto=format&fit=crop&w=1600&q=80",
  laptop:
    "https://images.unsplash.com/photo-1496181133206-80ce9b88a853?auto=format&fit=crop&w=1600&q=80",
  headphones:
    "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?auto=format&fit=crop&w=1600&q=80",
  earbuds:
    "https://images.unsplash.com/photo-1590658268037-6bf12165a8df?auto=format&fit=crop&w=1600&q=80",
  watch:
    "https://images.unsplash.com/photo-1434493789847-2f02dc6ca35d?auto=format&fit=crop&w=1600&q=80",
  gaming:
    "https://images.unsplash.com/photo-1606144042614-b2417e99c4e3?auto=format&fit=crop&w=1600&q=80",
  handheld:
    "https://images.unsplash.com/photo-1531525645387-7f14be1bdbbd?auto=format&fit=crop&w=1600&q=80",
  ai: "https://images.unsplash.com/photo-1677442136019-21780ecad995?auto=format&fit=crop&w=1600&q=80",
  chips:
    "https://images.unsplash.com/photo-1518770660439-4636190af475?auto=format&fit=crop&w=1600&q=80",
  tv: "https://images.unsplash.com/photo-1593359677879-a4bb92f829d1?auto=format&fit=crop&w=1600&q=80",
  duo: "https://images.unsplash.com/photo-1695048133142-1a20484d2569?auto=format&fit=crop&w=1600&q=80",
};

export const authors = {
  maya: {
    name: "Maya Chen",
    avatarUrl:
      "https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=128&q=80",
  },
  jordan: {
    name: "Jordan Hale",
    avatarUrl:
      "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=128&q=80",
  },
  priya: {
    name: "Priya Nair",
    avatarUrl:
      "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=128&q=80",
  },
  alex: {
    name: "Alex Rivera",
    avatarUrl:
      "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?auto=format&fit=crop&w=128&q=80",
  },
  sam: {
    name: "Sam Okonkwo",
    avatarUrl:
      "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=128&q=80",
  },
};

export const mockArticles: ArticleCard[] = [
  {
    id: "a0",
    title: "iPhone Duo review: Apple’s foldable after weeks as a daily driver",
    slug: "iphone-duo-review",
    excerpt:
      "Not a launch-day recap. After weeks of split-screen, pocket carry, and Touch ID in the power button, the 7.6-inch inner canvas is the product — if you stop unfolding it on a train.",
    featuredImage: contentImages.duo,
    badge: "REVIEW",
    kind: "review",
    category: "Mobile",
    categorySlug: "mobile",
    author: authors.maya,
    publishedAt: "2026-09-12T07:00:00.000Z",
    readingTime: "10 min read",
    score: 8.7,
  },
  {
    id: "a1",
    title: "iPhone 16 Pro Max review: the camera phone to beat in 2026",
    slug: "iphone-16-pro-max-review",
    excerpt:
      "Apple’s flagship finally feels like a leap — titanium, a 5x tetraprism, and all-day battery that survives a week of travel testing.",
    featuredImage: contentImages.iphone,
    badge: "REVIEW",
    kind: "review",
    category: "Mobile",
    categorySlug: "mobile",
    author: authors.maya,
    publishedAt: "2026-09-10T08:00:00.000Z",
    readingTime: "11 min read",
    score: 9.2,
  },
  {
    id: "a2",
    title: "Galaxy S24 Ultra hands-on: S Pen, AI, and a display that still leads",
    slug: "galaxy-s24-ultra-hands-on",
    excerpt:
      "We spent three days with Samsung’s Ultra before launch. The anti-reflective panel and on-device Galaxy AI are the real story.",
    featuredImage: contentImages.galaxy,
    badge: "HANDS ON",
    kind: "comparison",
    category: "Mobile",
    categorySlug: "mobile",
    author: authors.jordan,
    publishedAt: "2026-09-09T11:30:00.000Z",
    readingTime: "11 min read",
    score: 9.0,
  },
  {
    id: "a3",
    title: "Best laptops 2026: the 12 machines we’d actually buy",
    slug: "best-laptops-2026",
    excerpt:
      "From $700 Chromebooks to $3,500 creator rigs — our lab picks after 40 hours of battery, display, and keyboard testing.",
    featuredImage: contentImages.macbook,
    badge: "GUIDE",
    kind: "guide",
    category: "Laptops",
    categorySlug: "laptops",
    author: authors.priya,
    publishedAt: "2026-09-08T14:15:00.000Z",
    readingTime: "10 min read",
  },
  {
    id: "a4",
    title: "Breaking: Snapdragon 8 Gen 4 laptops leak with 22-hour battery claims",
    slug: "snapdragon-8-gen-4-laptop-leak",
    excerpt:
      "Qualcomm’s next silicon is headed to thin-and-light Windows machines first. Here is what the leaked slides actually say.",
    featuredImage: contentImages.chips,
    badge: "BREAKING",
    kind: "news",
    category: "News",
    categorySlug: "news",
    author: authors.sam,
    publishedAt: "2026-09-12T04:20:00.000Z",
    readingTime: "4 min read",
  },
  {
    id: "a5",
    title: "Sony WH-1000XM6 review: still the ANC king, now with smarter calls",
    slug: "sony-wh-1000xm6-review",
    excerpt:
      "A refined flagship rather than a reboot — better voice pickup, lighter clamps, and class-leading silence on long-haul flights.",
    featuredImage: contentImages.headphones,
    badge: "REVIEW",
    kind: "review",
    category: "Audio",
    categorySlug: "audio",
    author: authors.alex,
    publishedAt: "2026-09-07T09:00:00.000Z",
    readingTime: "10 min read",
    score: 8.9,
  },
  {
    id: "a6",
    title: "Pixel 10 Pro review: Google’s AI camera is no longer a gimmick",
    slug: "pixel-10-pro-review",
    excerpt:
      "Night Sight, Magic Editor, and a brighter LTPO panel make this the most complete Pixel yet — if you can live with the tensor heat.",
    featuredImage: contentImages.pixel,
    badge: "REVIEW",
    kind: "review",
    category: "Mobile",
    categorySlug: "mobile",
    author: authors.jordan,
    publishedAt: "2026-09-06T10:45:00.000Z",
    readingTime: "10 min read",
    score: 8.8,
  },
  {
    id: "a7",
    title: "How to transfer photos off a full iPhone without iCloud",
    slug: "how-to-transfer-iphone-photos-without-icloud",
    excerpt:
      "A clean, step-by-step guide for Windows and Mac — including the cable trick Apple does not mention in Settings.",
    featuredImage: contentImages.iphoneAlt,
    badge: "GUIDE",
    kind: "guide",
    category: "How-To",
    categorySlug: "how-to",
    author: authors.maya,
    publishedAt: "2026-09-05T16:00:00.000Z",
    readingTime: "8 min read",
  },
  {
    id: "a8",
    title: "Apple Watch Ultra 3 review: the adventure watch that finally lasts a week",
    slug: "apple-watch-ultra-3-review",
    excerpt:
      "Bigger battery, dual-frequency GPS, and a dive computer that we actually trusted on a weekend boat trip.",
    featuredImage: contentImages.watch,
    badge: "REVIEW",
    kind: "review",
    category: "Wearables",
    categorySlug: "wearables",
    author: authors.maya,
    publishedAt: "2026-09-04T12:00:00.000Z",
    readingTime: "10 min read",
    score: 8.6,
  },
  {
    id: "a9",
    title: "ROG Ally X 2 review: the Windows handheld that can replace a Steam Deck",
    slug: "rog-ally-x-2-review",
    excerpt:
      "A brighter VRR panel and a battery that survives a flight to Tokyo. PC gaming on the go finally feels finished.",
    featuredImage: contentImages.handheld,
    badge: "REVIEW",
    kind: "review",
    category: "Gaming",
    categorySlug: "gaming",
    author: authors.sam,
    publishedAt: "2026-09-03T13:20:00.000Z",
    readingTime: "9 min read",
    score: 8.4,
  },
  {
    id: "a10",
    title: "PS5 Pro restock deal: $80 off the bundle at Amazon today",
    slug: "ps5-pro-restock-deal",
    excerpt:
      "The Disc Edition bundle with an extra controller is the lowest price we have tracked since launch. Stock will not last.",
    featuredImage: contentImages.gaming,
    badge: "DEAL",
    kind: "deal",
    category: "Gaming",
    categorySlug: "gaming",
    author: authors.sam,
    publishedAt: "2026-09-11T07:10:00.000Z",
    readingTime: "3 min read",
  },
  {
    id: "a11",
    title: "Best noise-cancelling earbuds under $200 in 2026",
    slug: "best-anc-earbuds-under-200",
    excerpt:
      "We tested 18 pairs for commute noise, gym fit, and call quality. These six are the ones worth your money.",
    featuredImage: contentImages.earbuds,
    badge: "GUIDE",
    kind: "guide",
    category: "Audio",
    categorySlug: "audio",
    author: authors.alex,
    publishedAt: "2026-09-02T15:40:00.000Z",
    readingTime: "9 min read",
  },
  {
    id: "a12",
    title: "Windows 12 leak shows a lock screen that finally acts like a phone",
    slug: "windows-12-lock-screen-leak",
    excerpt:
      "Widgets, live activities, and a camera-key shortcut — Microsoft is borrowing the best ideas from Android 16.",
    featuredImage: contentImages.laptop,
    badge: "NEWS",
    kind: "news",
    category: "News",
    categorySlug: "news",
    author: authors.priya,
    publishedAt: "2026-09-01T18:00:00.000Z",
    readingTime: "5 min read",
  },
  {
    id: "a13",
    title: "On-device AI in 2026: what actually works on phones today",
    slug: "on-device-ai-phones-2026",
    excerpt:
      "We ran the same 12 prompts on iPhone, Galaxy, and Pixel. Offline translation is real. Most ‘AI cameras’ still are not.",
    featuredImage: contentImages.ai,
    badge: "NEWS",
    kind: "news",
    category: "News",
    categorySlug: "news",
    author: authors.jordan,
    publishedAt: "2026-08-30T09:30:00.000Z",
    readingTime: "7 min read",
  },
  {
    id: "a14",
    title: "OLED TV deal: 65-inch QD-OLED drops below $1,200 this weekend",
    slug: "oled-tv-weekend-deal",
    excerpt:
      "If you have been waiting for a bright, glare-free living-room panel, this is the first time we would click buy.",
    featuredImage: contentImages.tv,
    badge: "DEAL",
    kind: "deal",
    category: "News",
    categorySlug: "news",
    author: authors.alex,
    publishedAt: "2026-09-11T15:00:00.000Z",
    readingTime: "4 min read",
  },
];

export const mockProducts: ProductCard[] = [
  {
    id: "p0",
    name: "iPhone Duo",
    slug: "iphone-duo",
    imageUrl: contentImages.duo,
    category: "Mobile",
    categorySlug: "mobile",
    rating: 4.4,
    score: 8.7,
    verdict: "Great",
    reviewSlug: "iphone-duo-review",
    verdictLong:
      "Apple’s first foldable is the multitasking phone if you will relearn the hinge and enroll two fingers. Not the zoom phone. Not the one-hand walk-and-text phone.",
    pros: [
      "7.6-inch inner canvas plus iOS 27 Split View",
      "Nano-texture hides the crease in most light",
      "Duo Preview + 48MP main selfies beat the inner cam",
    ],
    cons: [
      "One-handed opens are how you drop a $1,999 phone",
      "No Face ID; wet Touch ID means passcode city",
      "No 5x tetraprism — 2x crop, then digital mush",
    ],
    specs: {
      Cover: "5.4-inch Ceramic Shield 2",
      Inner: "7.6-inch 120Hz Super Retina XDR",
      Chip: "A20 Pro",
      Cameras: "Dual 48MP Fusion, 2x crop",
      Battery: "4,700mAh split pack",
    },
  },
  {
    id: "p1",
    name: "iPhone 16 Pro Max",
    slug: "iphone-16-pro-max",
    imageUrl: contentImages.iphone,
    category: "Mobile",
    categorySlug: "mobile",
    rating: 4.6,
    score: 9.2,
    verdict: "Excellent",
    reviewSlug: "iphone-16-pro-max-review",
    verdictLong:
      "The camera-phone to beat if you will retrain Camera Control and treat 5x as a daylight specialist. Travel-day battery is real after Always-On dies. The slab is still a two-hand tax.",
    pros: [
      "Camera Control becomes a real two-stage shutter after a week",
      "5x tetraprism is honest in daylight and on stage",
      "Travel-day battery if Always-On and StandBy are off",
    ],
    cons: [
      "Light Press false-fires in pockets and thick cases",
      "6.9-inch reach and titanium heat during 4K60",
      "Box USB-C cable is charging-only in practice",
    ],
    specs: {
      Display: "6.9-inch Super Retina XDR, ProMotion 120Hz",
      Chip: "A18 Pro",
      Cameras: "48MP Fusion, 48MP Ultra Wide, 5x tetraprism",
      Battery: "22–26h mixed 5G weekdays; 7–9h screen-on",
      Charging: "USB-C PD, MagSafe",
    },
  },
  {
    id: "p2",
    name: "Galaxy S24 Ultra",
    slug: "galaxy-s24-ultra",
    imageUrl: contentImages.galaxy,
    category: "Mobile",
    categorySlug: "mobile",
    rating: 4.5,
    score: 9.0,
    verdict: "Excellent",
    reviewSlug: "galaxy-s24-ultra-hands-on",
    verdictLong:
      "Still the Android tool-slab: anti-glare glass you can read at noon, an S Pen that justifies Ultra money, and a 10x that is a daylight specialist — not an always-on superpower.",
    pros: [
      "Best outdoor readability in the current flagship class",
      "S Pen is a real work tool, not a nostalgia stub",
      "3x/10x daylight zoom that replaces a small travel camera",
    ],
    cons: [
      "Heavy, sharp-cornered, and easy to lose the pen",
      "10x and AI processing still lie in warm indoor light",
      "All-day, not two-day, at 120Hz on 5G",
    ],
    specs: {
      Display: "6.8-inch QHD+ AMOLED, anti-reflective, 120Hz",
      Chip: "Snapdragon 8 Gen 3 for Galaxy",
      Cameras: "200MP wide, UW, 3x, 10x tele",
      Battery: "5,000mAh class, 45W wired",
      Stylus: "Built-in S Pen with Bluetooth remote",
    },
  },
  {
    id: "p3",
    name: "Pixel 10 Pro",
    slug: "pixel-10-pro",
    imageUrl: contentImages.pixel,
    category: "Mobile",
    categorySlug: "mobile",
    rating: 4.4,
    score: 8.8,
    verdict: "Great",
    reviewSlug: "pixel-10-pro-review",
    verdictLong:
      "Best ugly-light stills in a compact body, with a panel that finally belongs outdoors. Magic Editor is a tool if you inspect the result. Tensor heat remains the asterisk.",
    pros: [
      "Night Sight still leads in kitchens and night streets",
      "Magic Editor is useful when you inspect at 100%",
      "LTPO panel finally belongs outdoors",
    ],
    cons: [
      "Tensor heat under camera + Maps + sun",
      "Battery is all-day-if-you-behave",
      "AI composites can fail while looking finished",
    ],
    specs: {
      Display: "LTPO OLED, bright outdoor mode, 120Hz",
      Chip: "Google Tensor (Pixel 10 Pro)",
      Cameras: "Wide, ultra-wide, telephoto + Night Sight",
      Battery: "6–7.5h screen-on mixed 5G",
      Charging: "20–30W USB-C PD class",
    },
  },
  {
    id: "p4",
    name: "MacBook Pro 16 (M4)",
    slug: "macbook-pro-16-m4",
    imageUrl: contentImages.macbook,
    category: "Laptops",
    categorySlug: "laptops",
    rating: 4.7,
    score: 9.4,
    verdict: "Excellent",
    verdictLong:
      "The desk-and-flight laptop we actually keep: Mini-LED volume, speakers that replace a travel bar, and a battery that survives a transatlantic if you murder ProMotion and keep a 96W-class brick for the hotel edit.",
    pros: [
      "Mini-LED volume and travel-bar speakers",
      "All-day-plus battery on mixed writing and light compile",
      "Ports that still include HDMI and MagSafe",
    ],
    cons: [
      "16-inch is a backpack tax, not a café slab",
      "ProMotion + HDR + a hot compile will eat the surplus",
      "Not the repairable or Windows-port story",
    ],
    specs: {
      Display: "16-inch Mini-LED, ProMotion",
      Chip: "Apple M4 Pro / Max class",
      Battery: "Lab 20h+ video; 10–14h mixed desk",
      Ports: "HDMI, SD, MagSafe, Thunderbolt",
      Weight: "2.1kg-class creator chassis",
    },
  },
  {
    id: "p5",
    name: "Sony WH-1000XM6",
    slug: "sony-wh-1000xm6",
    imageUrl: contentImages.headphones,
    category: "Audio",
    categorySlug: "audio",
    rating: 4.5,
    score: 8.9,
    verdict: "Great",
    reviewSlug: "sony-wh-1000xm6-review",
    verdictLong:
      "Still the pair we put in the suitcase first. Class-leading long-haul hush and better call mics — after you disable Speak-to-Chat and stop letting two laptops fight over the microphone.",
    pros: [
      "Best long-haul ANC in the common over-ear shape",
      "Clamp and glasses comfort past the XM5 sore spot",
      "Call mics that survive wind if helpers are off",
    ],
    cons: [
      "Speak-to-Chat will sabotage a flight at defaults",
      "Multipoint plus two mics is still a coin flip",
      "Cups get warm; the case is not small",
    ],
    specs: {
      Type: "Wireless over-ear, folding",
      ANC: "Adaptive + manual, class-leading low-end hush",
      Codecs: "SBC, AAC, LDAC (Android)",
      Battery: "~30h ANC on, USB-C quick charge",
      Multipoint: "Yes, with mic caveats",
    },
  },
  {
    id: "p6",
    name: "Apple Watch Ultra 3",
    slug: "apple-watch-ultra-3",
    imageUrl: contentImages.watch,
    category: "Wearables",
    categorySlug: "wearables",
    rating: 4.3,
    score: 8.6,
    verdict: "Great",
    reviewSlug: "apple-watch-ultra-3-review",
    verdictLong:
      "First Ultra we pack for a weekend without a negotiation. Dual-frequency GPS and a dive computer we trusted on a boat — if the Action Button is a mode key, not a siren, and the bright face does not eat the surplus.",
    pros: [
      "Weekend-capable battery with a Dirt face",
      "Dual-frequency GPS tracks that look like the path",
      "Recreational dive computer we actually used",
    ],
    cons: [
      "Bright faces and LTE erase the endurance story",
      "Sleep/recovery is fine, not oracle-class",
      "Size and salt want attention you have to give",
    ],
    specs: {
      Case: "49mm-class titanium Ultra",
      Battery: "4 mixed days typical; weekend-capable",
      GNSS: "Dual-frequency GPS",
      Water: "Dive-capable recreational computer",
      Controls: "Action Button, crown, siren",
    },
  },
  {
    id: "p7",
    name: "ROG Ally X 2",
    slug: "rog-ally-x-2",
    imageUrl: contentImages.handheld,
    category: "Gaming",
    categorySlug: "gaming",
    rating: 4.2,
    score: 8.4,
    verdict: "Great",
    reviewSlug: "rog-ally-x-2-review",
    verdictLong:
      "First Windows handheld we take across an ocean on purpose. VRR plus a 17W flight profile survive a long-haul — if you pause Windows Update and stop treating sleep like a Switch.",
    pros: [
      "VRR panel that belongs on a tray table",
      "Flight-profile battery that survives a long-haul",
      "Steam + Game Pass on grips with named TDP profiles",
    ],
    cons: [
      "Sleep/resume is still a Windows story",
      "High TDP unplugged is an hour-class toy",
      "Docks lie about charging; a 65W brick is part of the SKU",
    ],
    specs: {
      Display: "1080p-class VRR, brighter than prior Ally",
      TDP: "Named profiles ~10W to plugged-in 25–30W",
      Battery: "Flight-capable at 17W",
      OS: "Windows 11 + Armory Crate",
      Ports: "USB-C PD, microSD, audio",
    },
  },
  {
    id: "p8",
    name: "OnePlus 14",
    slug: "oneplus-14",
    imageUrl: contentImages.iphoneAlt,
    category: "Mobile",
    categorySlug: "mobile",
    rating: 4.2,
    score: 8.5,
    verdict: "Great",
    verdictLong:
      "The fluid, 100W-class daily driver we recommend when flagship cameras are a tax you will not use. Charge anxiety dies at lunch. Software extras still need a Saturday of turning off.",
    pros: [
      "100W-class charging that makes a lunch save real",
      "Fluid 120Hz software that still feels like old OnePlus",
      "Price under the Ultra tax for most commutes",
    ],
    cons: [
      "Zoom and night still trail Pixel / Ultra / Pro Max",
      "Alert slider nostalgia is not a camera",
      "Regional support and update years vary — check yours",
    ],
    specs: {
      Display: "6.7-inch-class 120Hz AMOLED",
      Chip: "Current Snapdragon 8-class flagship",
      Charging: "100W-class wired",
      Battery: "All-day with a 15-minute rescue",
      Software: "OxygenOS, near-stock extras",
    },
  },
  {
    id: "p9",
    name: "Xiaomi 15 Ultra",
    slug: "xiaomi-15-ultra",
    imageUrl: contentImages.galaxy,
    category: "Mobile",
    categorySlug: "mobile",
    rating: 4.2,
    score: 8.4,
    verdict: "Great",
    verdictLong:
      "Leica color you will either love or spend a week fighting, with charging that humiliates a Pro Max at a café. Import tax, HyperOS ads, and a camera bump that eats cases are the real-world bill.",
    pros: [
      "Leica stills with more optical ambition than the price",
      "Fast charge that makes a flagship pack feel small",
      "Value versus Ultra / Pro Max camera money",
    ],
    cons: [
      "HyperOS wants a Saturday of notification hygiene",
      "Camera bump and weight want a real case plan",
      "Global ROM / warranty is the import gotcha",
    ],
    specs: {
      Display: "6.7-inch-class LTPO AMOLED",
      Cameras: "Leica-tuned wide + dedicated tele",
      Charging: "90W-class wired, wireless on some SKUs",
      Battery: "All-day mixed; café-rescue charge",
      Software: "HyperOS (global vs CN matters)",
    },
  },
];

export const mockTrending: TrendingTopic[] = [
  { label: "iPhone Duo", href: "/reviews/iphone-duo-review" },
  { label: "iPhone 16 Pro Max", href: "/reviews/iphone-16-pro-max-review" },
  { label: "Galaxy S24 Ultra", href: "/reviews/galaxy-s24-ultra-hands-on" },
  { label: "MacBook Pro 16", href: "/products/macbook-pro-16-m4" },
  { label: "Best Laptops 2026", href: "/articles/best-laptops-2026" },
  { label: "PS5 Pro", href: "/articles/ps5-pro-restock-deal" },
];

export const navCategories = [
  { label: "Mobile", href: "/category/mobile" },
  { label: "Laptops", href: "/category/laptops" },
  { label: "Audio", href: "/category/audio" },
  { label: "Wearables", href: "/category/wearables" },
  { label: "Gaming", href: "/category/gaming" },
  { label: "How-To", href: "/category/how-to" },
  { label: "News", href: "/category/news" },
] as const;
