import type { GuidePick, GuideTabId, TopFiveGuides } from "@/lib/content/types";

const img = {
  iphone:
    "https://images.unsplash.com/photo-1695048133142-1a20484d2569?auto=format&fit=crop&w=1600&q=80",
  iphoneAlt:
    "https://images.unsplash.com/photo-1510557880182-3d4d3cba35a5?auto=format&fit=crop&w=1600&q=80",
  galaxy:
    "https://images.unsplash.com/photo-1610945415295-d9bbf067e59c?auto=format&fit=crop&w=1600&q=80",
  pixel:
    "https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?auto=format&fit=crop&w=1600&q=80",
  fold:
    "https://images.unsplash.com/photo-1610945264803-c22b62d2a7b3?auto=format&fit=crop&w=1600&q=80",
  macbook:
    "https://images.unsplash.com/photo-1517336714731-489689fd1ca8?auto=format&fit=crop&w=1600&q=80",
  laptop:
    "https://images.unsplash.com/photo-1496181133206-80ce9b88a853?auto=format&fit=crop&w=1600&q=80",
  laptopSilver:
    "https://images.unsplash.com/photo-1496181133206-80ce9b88a853?auto=format&fit=crop&w=1600&q=80",
  laptopDark:
    "https://images.unsplash.com/photo-1593642702821-c8da6771f0c6?auto=format&fit=crop&w=1600&q=80",
  laptopDesk:
    "https://images.unsplash.com/photo-1588872657578-7efd1f1555ed?auto=format&fit=crop&w=1600&q=80",
  headphones:
    "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?auto=format&fit=crop&w=1600&q=80",
  earbuds:
    "https://images.unsplash.com/photo-1590658268037-6bf12165a8df?auto=format&fit=crop&w=1600&q=80",
  earbudsWhite:
    "https://images.unsplash.com/photo-1606220945770-b5b6c2c55bf1?auto=format&fit=crop&w=1600&q=80",
  headphonesTan:
    "https://images.unsplash.com/photo-1546435770-a3e426bf472b?auto=format&fit=crop&w=1600&q=80",
  speaker:
    "https://images.unsplash.com/photo-1608043152269-423dbba4e7e1?auto=format&fit=crop&w=1600&q=80",
  watch:
    "https://images.unsplash.com/photo-1434493789847-2f02dc6ca35d?auto=format&fit=crop&w=1600&q=80",
  watchSport:
    "https://images.unsplash.com/photo-1579586337278-3befd40fd17a?auto=format&fit=crop&w=1600&q=80",
  watchBlack:
    "https://images.unsplash.com/photo-1523275335684-37898b6baf30?auto=format&fit=crop&w=1600&q=80",
  band: "https://images.unsplash.com/photo-1575311373937-040b8e1fd5b6?auto=format&fit=crop&w=1600&q=80",
  gaming:
    "https://images.unsplash.com/photo-1606144042614-b2417e99c4e3?auto=format&fit=crop&w=1600&q=80",
  handheld:
    "https://images.unsplash.com/photo-1531525645387-7f14be1bdbbd?auto=format&fit=crop&w=1600&q=80",
  controller:
    "https://images.unsplash.com/photo-1606144042614-b2417e99c4e3?auto=format&fit=crop&w=1600&q=80",
  switch:
    "https://images.unsplash.com/photo-1531525645387-7f14be1bdbbd?auto=format&fit=crop&w=1600&q=80",
};

function pick(
  partial: Omit<GuidePick, "rating"> & { rating?: number },
): GuidePick {
  return {
    rating: partial.rating ?? Math.round((partial.score / 2) * 10) / 10,
    ...partial,
  };
}

export const GUIDE_RANK_LABELS: Record<GuideTabId, string[]> = {
  smart: [
    "#1 Overall Best",
    "#2 Best Productivity",
    "#3 Best Camera",
    "#4 Best Value",
    "#5 Best Design",
  ],
  laptops: [
    "#1 Overall Best",
    "#2 Best Windows",
    "#3 Best Repairable",
    "#4 Best OLED",
    "#5 Best Value",
  ],
  wearables: [
    "#1 Overall Best",
    "#2 Best Adventure",
    "#3 Best Wear OS",
    "#4 Best Android",
    "#5 Best Fitness",
  ],
  audio: [
    "#1 Overall Best",
    "#2 Best Comfort",
    "#3 Best Ecosystem",
    "#4 Best Sound",
    "#5 Best Value",
  ],
  gaming: [
    "#1 Overall Best",
    "#2 Best PC Library",
    "#3 Best Console Value",
    "#4 Best Portable",
    "#5 Best Windows Handheld",
  ],
};

export const mockTopFive: TopFiveGuides = {
  smart: [
    pick({
      id: "g-smart-1",
      name: "iPhone 16 Pro Max",
      slug: "iphone-16-pro-max",
      imageUrl: img.iphone,
      category: "Smartphones",
      categorySlug: "mobile",
      subCategory: "Flagship",
      rank: 1,
      rankLabel: GUIDE_RANK_LABELS.smart[0],
      score: 9.2,
      verdict: "Excellent",
      pros: ["Battery life", "Tetraprism camera", "Display"],
      specs: {
        processor: "A18 Pro",
        display: "6.9\" 120Hz OLED",
        battery: "29h video",
      },
    }),
    pick({
      id: "g-smart-2",
      name: "Galaxy S24 Ultra",
      slug: "galaxy-s24-ultra",
      imageUrl: img.galaxy,
      category: "Smartphones",
      categorySlug: "mobile",
      subCategory: "Android flagship",
      rank: 2,
      rankLabel: GUIDE_RANK_LABELS.smart[1],
      score: 9.0,
      verdict: "Excellent",
      pros: ["S Pen", "Anti-glare panel", "10x zoom"],
      specs: {
        processor: "Snapdragon 8 Gen 3",
        display: "6.8\" LTPO AMOLED",
        battery: "5,000mAh",
      },
    }),
    pick({
      id: "g-smart-3",
      name: "Pixel 10 Pro",
      slug: "pixel-10-pro",
      imageUrl: img.pixel,
      category: "Smartphones",
      categorySlug: "mobile",
      subCategory: "Camera phone",
      rank: 3,
      rankLabel: GUIDE_RANK_LABELS.smart[2],
      score: 8.8,
      verdict: "Great",
      pros: ["AI camera", "Clean software", "Size"],
      specs: {
        processor: "Tensor G5",
        display: "6.7\" LTPO OLED",
        battery: "5,000mAh",
      },
    }),
    pick({
      id: "g-smart-4",
      name: "OnePlus 14",
      slug: "oneplus-14",
      imageUrl: img.iphoneAlt,
      category: "Smartphones",
      categorySlug: "mobile",
      subCategory: "Value flagship",
      rank: 4,
      rankLabel: GUIDE_RANK_LABELS.smart[3],
      score: 8.5,
      verdict: "Great",
      pros: ["100W charging", "Fluidity", "Price"],
      specs: {
        processor: "Snapdragon 8 Elite",
        display: "6.78\" 120Hz",
        battery: "6,000mAh",
      },
    }),
    pick({
      id: "g-smart-5",
      name: "Nothing Phone 3",
      slug: "nothing-phone-3",
      imageUrl: img.fold,
      category: "Smartphones",
      categorySlug: "mobile",
      subCategory: "Design",
      rank: 5,
      rankLabel: GUIDE_RANK_LABELS.smart[4],
      score: 8.3,
      verdict: "Great",
      pros: ["Glyph interface", "Clean OS", "Price"],
      specs: {
        processor: "Snapdragon 8s Gen 4",
        display: "6.7\" OLED",
        battery: "4,700mAh",
      },
    }),
  ],
  laptops: [
    pick({
      id: "g-laptop-1",
      name: "MacBook Pro 16 (M4)",
      slug: "macbook-pro-16-m4",
      imageUrl: img.macbook,
      category: "Laptops",
      categorySlug: "laptops",
      subCategory: "Creator laptop",
      rank: 1,
      rankLabel: GUIDE_RANK_LABELS.laptops[0],
      score: 9.4,
      verdict: "Excellent",
      pros: ["Battery", "Mini-LED", "Speakers"],
      specs: {
        processor: "Apple M4 Pro",
        display: "16.2\" Liquid Retina XDR",
        battery: "22h video",
      },
    }),
    pick({
      id: "g-laptop-2",
      name: "Dell XPS 14 (2026)",
      slug: "dell-xps-14-2026",
      imageUrl: img.laptopSilver,
      category: "Laptops",
      categorySlug: "laptops",
      subCategory: "Windows ultrabook",
      rank: 2,
      rankLabel: GUIDE_RANK_LABELS.laptops[1],
      score: 8.9,
      verdict: "Great",
      pros: ["Build", "Keyboard", "OLED option"],
      specs: {
        processor: "Core Ultra 9 285H",
        display: "14.5\" 3.2K OLED",
        battery: "16h office",
      },
    }),
    pick({
      id: "g-laptop-3",
      name: "Framework Laptop 13",
      slug: "framework-laptop-13-2026",
      imageUrl: img.laptop,
      category: "Laptops",
      categorySlug: "laptops",
      subCategory: "Modular",
      rank: 3,
      rankLabel: GUIDE_RANK_LABELS.laptops[2],
      score: 8.7,
      verdict: "Great",
      pros: ["Repairability", "Ports", "Keyboard"],
      specs: {
        processor: "Ryzen AI 9 365",
        display: "13.5\" 2.8K",
        battery: "13h",
      },
    }),
    pick({
      id: "g-laptop-4",
      name: "ASUS Zenbook 14 OLED",
      slug: "asus-zenbook-14-oled-2026",
      imageUrl: img.laptopDark,
      category: "Laptops",
      categorySlug: "laptops",
      subCategory: "OLED ultrabook",
      rank: 4,
      rankLabel: GUIDE_RANK_LABELS.laptops[3],
      score: 8.5,
      verdict: "Great",
      pros: ["OLED punch", "Weight", "NumberPad"],
      specs: {
        processor: "Core Ultra 7 256V",
        display: "14\" 3K OLED",
        battery: "18h",
      },
    }),
    pick({
      id: "g-laptop-5",
      name: "Lenovo Yoga Slim 7x",
      slug: "lenovo-yoga-slim-7x",
      imageUrl: img.laptopDesk,
      category: "Laptops",
      categorySlug: "laptops",
      subCategory: "Snapdragon PC",
      rank: 5,
      rankLabel: GUIDE_RANK_LABELS.laptops[4],
      score: 8.4,
      verdict: "Great",
      pros: ["Battery", "Silent", "Price"],
      specs: {
        processor: "Snapdragon X Elite",
        display: "14.5\" 3K OLED",
        battery: "20h",
      },
    }),
  ],
  wearables: [
    pick({
      id: "g-wear-1",
      name: "Garmin Fenix 8",
      slug: "garmin-fenix-8",
      imageUrl: img.watchSport,
      category: "Wearables",
      categorySlug: "wearables",
      subCategory: "Multisport watch",
      rank: 1,
      rankLabel: GUIDE_RANK_LABELS.wearables[0],
      score: 8.8,
      verdict: "Great",
      pros: ["Battery", "Maps", "Training load"],
      specs: {
        processor: "Garmin Elevate",
        display: "1.4\" AMOLED / MIP",
        battery: "16 days smart",
      },
    }),
    pick({
      id: "g-wear-2",
      name: "Apple Watch Ultra 3",
      slug: "apple-watch-ultra-3",
      imageUrl: img.watch,
      category: "Wearables",
      categorySlug: "wearables",
      subCategory: "Adventure watch",
      rank: 2,
      rankLabel: GUIDE_RANK_LABELS.wearables[1],
      score: 8.6,
      verdict: "Great",
      pros: ["Build", "Dive computer", "Apps"],
      specs: {
        processor: "S10 SiP",
        display: "49mm LTPO OLED",
        battery: "72h adventure",
      },
    }),
    pick({
      id: "g-wear-3",
      name: "Galaxy Watch 7 Ultra",
      slug: "galaxy-watch-7-ultra",
      imageUrl: img.watchBlack,
      category: "Wearables",
      categorySlug: "wearables",
      subCategory: "Wear OS",
      rank: 3,
      rankLabel: GUIDE_RANK_LABELS.wearables[2],
      score: 8.4,
      verdict: "Great",
      pros: ["Sapphire", "BioActive", "Samsung apps"],
      specs: {
        processor: "Exynos W1000",
        display: "1.5\" Super AMOLED",
        battery: "3 days",
      },
    }),
    pick({
      id: "g-wear-4",
      name: "Pixel Watch 3",
      slug: "pixel-watch-3",
      imageUrl: img.watchBlack,
      category: "Wearables",
      categorySlug: "wearables",
      subCategory: "Wear OS",
      rank: 4,
      rankLabel: GUIDE_RANK_LABELS.wearables[3],
      score: 8.3,
      verdict: "Great",
      pros: ["Fit design", "Fitbit", "Pixel extras"],
      specs: {
        processor: "Tensor SW",
        display: "1.3\" AMOLED",
        battery: "24h + Fast Charge",
      },
    }),
    pick({
      id: "g-wear-5",
      name: "Whoop 5.0",
      slug: "whoop-5-0",
      imageUrl: img.band,
      category: "Wearables",
      categorySlug: "wearables",
      subCategory: "Fitness band",
      rank: 5,
      rankLabel: GUIDE_RANK_LABELS.wearables[4],
      score: 8.1,
      verdict: "Great",
      pros: ["Recovery", "Screen-free", "Strain"],
      specs: {
        processor: "Whoop PPG 5",
        display: "No screen",
        battery: "14 days",
      },
    }),
  ],
  audio: [
    pick({
      id: "g-audio-1",
      name: "Sony WH-1000XM6",
      slug: "sony-wh-1000xm6",
      imageUrl: img.headphones,
      category: "Audio",
      categorySlug: "audio",
      subCategory: "ANC headphones",
      rank: 1,
      rankLabel: GUIDE_RANK_LABELS.audio[0],
      score: 8.9,
      verdict: "Great",
      pros: ["ANC", "Comfort", "Calls"],
      specs: {
        processor: "QN3 + 8 mics",
        display: "App EQ / 360 Reality",
        battery: "30h ANC on",
      },
    }),
    pick({
      id: "g-audio-2",
      name: "Bose QuietComfort Ultra 2",
      slug: "bose-qc-ultra-2",
      imageUrl: img.headphonesTan,
      category: "Audio",
      categorySlug: "audio",
      subCategory: "ANC headphones",
      rank: 2,
      rankLabel: GUIDE_RANK_LABELS.audio[1],
      score: 8.7,
      verdict: "Great",
      pros: ["Clamp comfort", "Immersive audio", "Silence"],
      specs: {
        processor: "Bose CustomTune",
        display: "App spatial modes",
        battery: "24h ANC on",
      },
    }),
    pick({
      id: "g-audio-3",
      name: "AirPods Pro 3",
      slug: "airpods-pro-3",
      imageUrl: img.earbudsWhite,
      category: "Audio",
      categorySlug: "audio",
      subCategory: "ANC earbuds",
      rank: 3,
      rankLabel: GUIDE_RANK_LABELS.audio[2],
      score: 8.6,
      verdict: "Great",
      pros: ["H2 ANC", "Transparency", "Find My"],
      specs: {
        processor: "Apple H2",
        display: "Adaptive Audio",
        battery: "7h + case 30h",
      },
    }),
    pick({
      id: "g-audio-4",
      name: "Sennheiser Momentum 4",
      slug: "sennheiser-momentum-4",
      imageUrl: img.headphonesTan,
      category: "Audio",
      categorySlug: "audio",
      subCategory: "Wireless headphones",
      rank: 4,
      rankLabel: GUIDE_RANK_LABELS.audio[3],
      score: 8.4,
      verdict: "Great",
      pros: ["Tonality", "Battery", "Build"],
      specs: {
        processor: "Sennheiser Sound+",
        display: "App EQ",
        battery: "60h",
      },
    }),
    pick({
      id: "g-audio-5",
      name: "Nothing Ear 3",
      slug: "nothing-ear-3",
      imageUrl: img.earbuds,
      category: "Audio",
      categorySlug: "audio",
      subCategory: "ANC earbuds",
      rank: 5,
      rankLabel: GUIDE_RANK_LABELS.audio[4],
      score: 8.2,
      verdict: "Great",
      pros: ["Price", "Transparency", "Case"],
      specs: {
        processor: "Nothing Audio",
        display: "ChatGPT button",
        battery: "8.5h + case 40h",
      },
    }),
  ],
  gaming: [
    pick({
      id: "g-game-1",
      name: "PlayStation 5 Pro",
      slug: "ps5-pro",
      imageUrl: img.gaming,
      category: "Gaming",
      categorySlug: "gaming",
      subCategory: "Console",
      rank: 1,
      rankLabel: GUIDE_RANK_LABELS.gaming[0],
      score: 9.0,
      verdict: "Excellent",
      pros: ["PSSR 4K", "Game library", "DualSense"],
      specs: {
        processor: "Zen 2 + RDNA Pro",
        display: "8K / 4K 120Hz",
        battery: "Wall powered",
      },
    }),
    pick({
      id: "g-game-2",
      name: "Steam Deck OLED 2",
      slug: "steam-deck-oled-2",
      imageUrl: img.handheld,
      category: "Gaming",
      categorySlug: "gaming",
      subCategory: "PC handheld",
      rank: 2,
      rankLabel: GUIDE_RANK_LABELS.gaming[1],
      score: 8.7,
      verdict: "Great",
      pros: ["Steam library", "OLED", "Desktop mode"],
      specs: {
        processor: "AMD APU 2026",
        display: "7.4\" 90Hz HDR OLED",
        battery: "3–12h",
      },
    }),
    pick({
      id: "g-game-3",
      name: "Xbox Series X 2TB",
      slug: "xbox-series-x-2tb",
      imageUrl: img.controller,
      category: "Gaming",
      categorySlug: "gaming",
      subCategory: "Console",
      rank: 3,
      rankLabel: GUIDE_RANK_LABELS.gaming[2],
      score: 8.6,
      verdict: "Great",
      pros: ["Game Pass", "Quiet", "Storage"],
      specs: {
        processor: "Zen 2 + RDNA 2",
        display: "4K 120Hz",
        battery: "Wall powered",
      },
    }),
    pick({
      id: "g-game-4",
      name: "Nintendo Switch 2",
      slug: "nintendo-switch-2",
      imageUrl: img.switch,
      category: "Gaming",
      categorySlug: "gaming",
      subCategory: "Hybrid console",
      rank: 4,
      rankLabel: GUIDE_RANK_LABELS.gaming[3],
      score: 8.5,
      verdict: "Great",
      pros: ["First-party", "Docked 4K", "Portable"],
      specs: {
        processor: "T239 custom",
        display: "8\" 120Hz LCD",
        battery: "6.5h",
      },
    }),
    pick({
      id: "g-game-5",
      name: "ROG Ally X 2",
      slug: "rog-ally-x-2",
      imageUrl: img.handheld,
      category: "Gaming",
      categorySlug: "gaming",
      subCategory: "Windows handheld",
      rank: 5,
      rankLabel: GUIDE_RANK_LABELS.gaming[4],
      score: 8.4,
      verdict: "Great",
      pros: ["VRR panel", "Battery", "Xbox Game Pass"],
      specs: {
        processor: "Z2 Extreme",
        display: "7\" 120Hz VRR",
        battery: "80Wh",
      },
    }),
  ],
};
